### ISSUE TITLE
requirements.txt file is missing

### ISSUE THREAD

**Issue by yanaiela** [AkariAsai/logic_guided_qa#1]
Hi,

Thanks for releasing the code!
It seems like the requirements.txt file is missing.

**Comment by AkariAsai** [comment]
Thank you for pointing it out! I've uploaded `requirements.txt` [here](https://github.com/AkariAsai/logic_guided_qa/blob/master/requirements.txt). Please let me know if you find any issues (e.g., missing requirements)
